GET http://localhost:4000/playlist/649d7447e7a0d197e0bb6d3c/songs

### Get all playlists
GET http://localhost:4000/playlist/all

###
POST http://localhost:4000/files/new-metadata
Content-Type: application/json

{
    "fileName": "name1 ",
    "fileNameFormatted": "name1%20",
    "filePath": "path1",
    "fileSize": 1,
    "fileType": "type1"
}

### New Playlist
POST http://localhost:4000/files/new-playlist
Content-Type: application/json

{
  "name": "TestPlaylist",
  "songs": [
  ]
}

### New songs in a playlist
POST http://localhost:4000/playlist/649d7447e7a0d197e0bb6d3c/add-songs/
Content-Type: application/json

{
    "fileName": "name1 ",
    "fileNameFormatted": "name1%20",
    "filePath": "path1",
    "fileSize": 1,
    "fileType": "type1"
}

###
DELETE http://localhost:4000/files/delete/64994ac136405f0805bb806f

